#
# Modified https://github.com/moby/buildkit/blob/81d49f78197cd471bb92ed800a4873384389bfd4/.github/workflows/buildx-image.yml
#

# source  latest
# dest    buildx-stable-1
# result  ghcr.io/sectorlabs/buildkit:latest   > ghcr.io/sectorlabs/buildkit:buildx-stable-1
#         ghcr.io/sectorlabs/buildkit:rootless > ghcr.io/sectorlabs/buildkit:buildx-stable-1-rootless
#
# source  v0.8.1
# dest    buildx-stable-1
# result  ghcr.io/sectorlabs/buildkit:v0.8.1          > ghcr.io/sectorlabs/buildkit:buildx-stable-1
#         ghcr.io/sectorlabs/buildkit:v0.8.1-rootless > ghcr.io/sectorlabs/buildkit:buildx-stable-1-rootless
name: Tag stable

on:
  workflow_dispatch:
    inputs:
      source-tag:
        description: 'BuildKit source Docker tag'
        required: true
        default: 'latest'
      dest-tag:
        description: 'Default BuildKit Docker tag for buildx'
        required: true
        default: 'buildx-stable-1'
      dry-run:
        description: 'Dry run'
        required: false
        default: 'true'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  SETUP_BUILDX_VERSION: "edge"
  REPO_SLUG_TARGET: "sectorlabs/buildkit"

jobs:
  create:
    name: Create

    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        flavor:
          - ''
          - 'rootless'

    steps:
      - name: Login to Packages Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: ${{ env.SETUP_BUILDX_VERSION }}
          driver-opts: image=ghcr.io/sectorlabs/buildkit:latest

      - name: Create
        run: |
          DRYRUN_FLAG=""
          if [ "${{ github.event.inputs.dry-run }}" = "true" ]; then
            DRYRUN_FLAG="--dry-run"
          fi

          SOURCE_TAG="${{ github.event.inputs.source-tag }}"
          DEST_TAG="${{ github.event.inputs.dest-tag }}"
          if [ "${{ matrix.flavor }}" != "" ]; then
            if [ "$SOURCE_TAG" = "latest" ]; then
              SOURCE_TAG="${{ matrix.flavor }}"
            else
              SOURCE_TAG="${SOURCE_TAG}-${{ matrix.flavor }}"
            fi
            DEST_TAG="${DEST_TAG}-${{ matrix.flavor }}"
          fi

          set -x
          docker buildx imagetools create ${DRYRUN_FLAG} --tag \
            "ghcr.io/${{ env.REPO_SLUG_TARGET }}:${DEST_TAG}" \
            "ghcr.io/${{ env.REPO_SLUG_TARGET }}:${SOURCE_TAG}"
